import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

export default function Home() {

  const [emailErrorMsg, setEmailErrorMsg] = useState(false);
  const [passwordErrorMsg, setPasswordErrorMsg] = useState(false);

  function validateEmail(value: string) : void {
    setEmailErrorMsg(
      value.search(/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/g) < 0 ? true : false
    )
  }

  function validatePassword(value: string) : void {
    setPasswordErrorMsg(value.length < 6 ? true : false)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>

        <h2 className={styles.title} >Login</h2>
        <form className={styles.form} >

          <label className="" >Email</label>
          <input 
            onChange={e => validateEmail(e.target.value)}
            className={styles.input}
            name="email"
            type="text" />
          {
            emailErrorMsg ?
              <p className={styles.errorMsg} >Email inválido.</p>
              : null
          }

          <label className="" >Senha</label>
          <input
            onChange={e => validatePassword(e.target.value)}
            className={styles.input}
            name="password"
            type="password" />

          {
            passwordErrorMsg ?
              <p className={styles.errorMsg} >Senha deve conter no mínimo 6 caracteres.</p>
              : null
          }

        </form>

      </main>
    </>
  );
}
