import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState, FormEvent, useEffect } from "react";
import { useRouter } from "next/router";


export default function Home() {

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const [emailErrorMsg, setEmailErrorMsg] = useState(true);
  const [passwordErrorMsg, setPasswordErrorMsg] = useState(true);
  const [submitErrorMsg, setSubmitErrorMsg] = useState(false);

  const router = useRouter();


  // Check if email match the default pattern
  function validateEmail(value: string) : void {
    if(value.search(/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/g) < 0){
      setEmailErrorMsg(true)
    } else {
      setEmailErrorMsg(false)
      setEmail(value)
    }
  }

  // Check if password follows the rule
  function validatePassword(value: string) : void {
    if(value.length < 6){
      setPasswordErrorMsg(true)
    } else {
      setPasswordErrorMsg(false)
      setPassword(value)
    }
  }


  // Do a POST request and redirects if answer is positive
  async function onSubmit(event: FormEvent<HTMLFormElement>){
    event.preventDefault()
    if(emailErrorMsg == false && passwordErrorMsg == false){
      setSubmitErrorMsg(false)
      const res = await fetch('/api/submit', {
        method: 'POST',
        body: JSON.stringify({
          email: email,
          password: password
        })
      })
      if(res.ok){
        router.push({
          pathname: "/user",
          query: {
            email: email,
            password: password
          }
        })
      }
    } else {
      setSubmitErrorMsg(true)
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>

        <h2 className={styles.title} >Login</h2>

        <form className={styles.form} onSubmit={onSubmit} >

          <label className="" >Email</label>
          <input 
            onChange={e => validateEmail(e.target.value)}
            className={styles.input}
            name="email"
            type="email" />
          {
            emailErrorMsg ?
              <p className={styles.errorMsg} >Email inválido.</p>
              : null
          }

          <label className="" >Senha</label>
          <input
            onChange={e => validatePassword(e.target.value)}
            className={styles.input}
            name="password"
            type="password" />

          {
            passwordErrorMsg ?
              <p className={styles.errorMsg} >Senha deve conter no mínimo 6 caracteres.</p>
              : null
          }

          <button 
            className={styles.submitBtn}
            type="submit" >Enviar</button>
          {
            submitErrorMsg ?
              <p className={styles.errorMsg} >Preencha os campos corretamente.</p>
              : null
          }
        </form>

      </main>
    </>
  );
}
